中野(6-1)404,500のエラーページを追加しました.
BoYoRyo/ex-emp-management-bugfix pull request #7
Opened 2022-08-24 08:20 UTC by BoYoRyo

2022-08-24 08:22 UTC, BoYoRyo commented
レビューお願いします。

2022-08-24 08:33 UTC, igamasayuki requested changes
GrobalExceptionHandlerも追加してください。

差し戻しますので、再度pushして管理シートより再レビュー依頼をしてください。
(この場合、push後、再度プルリクを作る必要はありません。)

2022-08-24 08:47 UTC, BoYoRyo commented
レビューありがとうございます。
確認お願いします。

2022-08-24 08:49 UTC, igamasayuki requested changes
気になる点をコメントしました。
差し戻しますので、再度pushして管理シートより再レビュー依頼をしてください。
(この場合、push後、再度プルリクを作る必要はありません。)

2022-08-24 08:49 UTC, igamasayuki commented on src/main/java/jp/co/sample/emp_management/common/GlobalExceptionHandler.java
> +		return null;
メールは送る必要はありませんが、Errorログは吐くようにしてください。

2022-08-24 09:23 UTC, BoYoRyo commented
レビューありがとうございます。
ログを吐くためための記述を消してしまっていたんですね、、、
メールも自動的に送られてしまうと思っていましたが、送るためにはLogback-spring.xmlに設定をしておかないと送られないということですね！

2022-08-24 09:23 UTC, BoYoRyo commented
確認お願いします。

2022-08-25 01:10 UTC, igamasayuki commented
> レビューありがとうございます。 ログを吐くためための記述を消してしまっていたんですね、、、 メールも自動的に送られてしまうと思っていましたが、送るためにはLogback-spring.xmlに設定をしておかないと送られないということですね！

そういうことです！

2022-08-25 01:11 UTC, igamasayuki approved these changes
問題ありませんので承認いたします。

2022-08-25 01:11 UTC, merged